version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: retailpulse-db
    restart: always
    environment:
      POSTGRES_USER: retailpulse
      POSTGRES_PASSWORD: retailpulse123
      POSTGRES_DB: retailpulse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
